name: Build Bin

on: [push]

jobs:
  build_and_test:
    name: Rust project
    runs-on: macos-11
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
      - run: go build
