name: Build Bin

on: [push]

jobs:
  build_and_test:
    name: Go Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.10'
      - run: go build
