name: Use Bin

on: [push]

jobs:
  usage-ubuntu:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        node: [ '10', '8' ]
    name: Npx ${{ matrix.node }} test ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npx hellpack eslint

  usage-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        node: [ '10', '8' ]
    name: Npx ${{ matrix.node }} test macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npx hellpack eslint

  usage-ubuntu-latest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '10', '8' ]
    name: Npx ${{ matrix.node }} test ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npx hellpack eslint
